# Should server operators bypass the filters?
op-bypass: true

# Should players be denied to join if their name contains bad words?
kick-on-bad-name: true

# Which events should be checked for bad words?
checks:
  chat: true
  sign: true
  book: true
  command: true
  anvil-name: true
  nametag-use: true

# Should detections that contain filtered words be logged in console
log-detections: true

# Commands of which arguments should be checked.
# It's recommended to list all private message commands and their aliases
# and every command that allows changing item name and etc.
filtered-commands:
  - msg
  - w
  - say
  - me

# These characters are replaced by the character on the right before processing.
replacements:
  '0': o
  '1': i
  '3': e
  '4': a
  '5': s
  '7': t
  '9': g
  '$': s
  '@': a

##### FILTERS
# Filters are processed in order from top to bottom
# You can have an unlimited number of filters.
###############################################################
# Each filter has a list of "matches". These are words that are checked for the filter.
# Types of matches:
#   - "fullword" Checks if the sentence contains this word. It must be surrounded by spaces.
#                Besides that, the filter is smart and will ignore any characters in between the word.
#                You can use the * character to bypass the limitation of needing a space: "test*" will match on "testsomething"
#   - "contain"  Checks if the sentence contains the string, the string may be part of another word.
#                Will ignore spaces inside the word unless they're used in an obviously spammy way.
#   - "regex"    Match a simple regex on the string. No smartness involved.
# By default the "fullword" match type is used.

###############################################################
# Each filter can have an unlimited number of "actions". Possible "action" types:
#   - "message: <message>" - sends a message to player who triggered the filter
#   - "command: <command>" - executes command as console.
# Placeholders available for all actions:
# %player% - name of the player who triggered the filter

filter:
  severe:
    action:
      - "command: tempmute %player% 4h Używanie obraźliwych słów"
    match:
      - nigger: "contain"
      - nibber: "contain"
      - niga: "contain"
      - niba: "contain"
      - pedal: "contain"
      - niger: "contain"
      - zjeb
      - chuj
      - huj
      - 卐: "contain"
      - 卍: "contain"
  normal:
    action:
      - "ghost"
    match:
      - hitler: "contain"
      - kurwa
      - (kurw[a-z]*): "regex"
      - (jeba[a-zęóąśłżźćń]*): "regex"
      - (pierd[ao][^ł]l*): "regex"
      - (cip[a-zęóąśłżźćń]*): "regex"
      - (pi[zź]d): "regex"
      - (g[^łl]([óo]wn)): "regex"
      - (dup[ay]): "regex"
      - (dupie): "regex"
      - (kutas): "regex"
      - (penis): "regex"
      - (dziwk[aoi]): "regex"
      - (dziwek): "regex"
  advertise:
    action:
      - "ghost"
    match:
      - ([ &.,]|^)([\w]{5,})([., ]){1,}(pl|com|org|net|biz|mobi|kz|tk|server.pro|serv.nu)([ &.,]|$): "regex"
      - ([\d]{1,3}[.,]{1,}){3,}([\d]{1,3}): "regex"
      - aternos

# Messages used by the plugin
messages:
  no-permission: "Censura - &cNie masz uprawnień, by to zrobić."
  no-such-command: "Censura - &cNie istnieje taka komenda."
  config-reloaded: "Censura - &aKonfiguracja przeładowana."
  kick-bad-name: "Censura\n&cTwój nick zawiera zakazane słowa!"

# Regex whitelist is configured in RegexMatch.